site_name: tracelet
repo_url: https://github.com/prassanna-ravishankar/tracelet
site_url: https://prassanna-ravishankar.github.io/tracelet
site_description: Tracelet is an automagic pytorch metric exporter
site_author: Prassanna Ravishankar
edit_uri: edit/main/docs/
repo_name: prassanna-ravishankar/tracelet
copyright: Maintained by <a href="https://prassanna-ravishankar.com">prassanna-ravishankar</a>.

nav:
  - Home: index.md
  - Modules: modules.md
  - Examples: examples.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [tracelet]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prassanna-ravishankar/tracelet
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/tracelet

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
